# Generated by Django 5.2.2 on 2025-06-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=20),
        ),
    ]
